sudo: required
services:
  - docker

before_install:
  - docker build -t olgamikholenko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true olgamikholenko/react-test npm test

after_success:
  - docker build -t olgamikholenko/multi-client ./client
  - docker build -t olgamikholenko/multi-nginx ./nginx
  - docker build -t olgamikholenko/multi-server ./server
  - docker build -t olgamikholenko/multi-worker ./worker
